blank_issues_enabled: false
contact_links:
  - name: 使用提问 / Questions
    url: https://github.com/DocJlm/InkCV/discussions
    about: 使用上的疑问请到 Discussions 提问。Please ask usage questions in Discussions.
